name = "P.O.S.I-SW"
fullname = "Package Online Service Installer Software"
description = f"{fullname} is a tool to download different stuff from the internet such as GitHub, YouTube, MC and more!"
CopyrightText = "P.O.S.I-SW © 2022"
version = "1.0.2"